name: 'rc-deploy'
description: 'Cause the deployment of the RC for the specified environment'
inputs:
  service-name:
    description: "Service Name"
    required: true
  environment:
    description: "Target environment"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
       echo not implemented
      shell: bash