name: 'deploy-specification'
description: 'Deploys a given specification to an environment'
inputs:
  spec:
    description: "Deployment specification"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
         export APP_SPEC=${{ inputs.spec }}
         
         ls -la /
         
         stacks=$(cdk list)
         echo deploying stacks $stacks
         cdk deploy --require-approval never $stacks
      shell: bash