name: 'deploy-specification'
description: 'Deploys a given specification to an environment'
inputs:
  spec:
    description: "Deployment specification"
    required: true
  mode:
    description: "Deployment mode (service / env)"
    required: false
    default: 'service'
runs:
  using: 'docker'
  image: 'Dockerfile.action'
  args:
    - ${{ inputs.spec }}
    - ${{ inputs.mode }}