name: 'deploy-specification'
description: 'Deploys a given specification to an environment'
inputs:
  spec:
    description: "Deployment specification"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.spec }}