name: 'resolve-env'
description: 'Resolve the deployment environment name'
outputs:
  environment:
    description: "Environment name which was resolved by the action"
    value: ${{ steps.resolver.outputs.target_env }}
runs:
  using: "composite"
  steps:
    - run: |
          event_name=$GITHUB_EVENT_NAME
          echo github event name $event_name

          if [ "$event_name" = "pull_request" ]; then
             git_ref=$GITHUB_HEAD_REF
          else
             git_ref=$GITHUB_REF
          fi
          echo git ref $git_ref

          branch_name=$(echo $git_ref | sed -e 's/^refs\/heads\///')
          echo branch name $branch_name

          if [ "$branch_name" = "main" ] || [ "$branch_name" = "master" ]; then
              target_env=ci
          else
             user_name=$(echo $GITHUB_ACTOR | sed -e 's/[^[:alnum:]]+/_/g')
             user_name=$(echo $user_name | sed -e 's/\(.*\)/\L\1/')
             echo user name $user_name
             target_env=dev$user_name
          fi

          if [ "${{ inputs.environment }}" != "auto" ]; then
             target_env=${{ inputs.environment }}
          elif [ "$branch_name" = "main" ] || [ "$branch_name" = "master" ]; then
            
          else
             
          fi

          echo ::set-output name=target_env::$target_env

      shell: bash
      id: resolver