name: 'update-rc-version'
description: 'Updates the Service RC version to the current git SHA'
inputs:
  type:
    description: "Application type (frontend / backend)"
    default: "backend"
runs:
  using: "composite"
  steps:
    - run: |
        app_type = ${{ inputs.type }}
        service_name=$GITHUB_REPOSITORY
        service_name=$(echo $service_name | sed -e 's/^agwafarm\///')
        service_name=$(echo $service_name | sed -e 's/^agwa\-//')

        if [ "$service_name" = "cloud-components" ]; then
             service_name=cloud-parent
        fi

        param_name=/infra/rc-version/$service_name
        param_value=$GITHUB_SHA

        echo ssm param name $param_name
        echo ssm param value $param_value
        
        aws ssm put-parameter --type String --overwrite --name $param_name --value $param_value --tags Key=appType,Value=$app_type
      shell: bash