name: 'rc-promote'
description: 'Updates the service RC version for the environment'
inputs:
  service-name:
    description: "Service Name"
    required: true
  version:
    description: "RC version"
    required: true
  environment:
    description: "Target environment"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        # aws ssm get-parameters-by-path --no-paginate --path /infra/rc-version/dev-eyalperry
        param_name=/infra/rc-version/${{ inputs.environment }}/${{ inputs.service-name }}
        echo ssm param name $param_name
        param_value=${{ inputs.version }}
        echo ssm param value $param_value
        aws ssm put-parameter --type String --overwrite --name $param_name --value $param_value
      shell: bash