name: 'rc-promote'
description: 'Updates the service RC version for the environment'
inputs:
  service-name:
    description: "Service Name"
    required: true
  version:
    description: "RC version"
    required: true
  environment: "Target environment"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        param_name=/infra/rc-version/${{ inputs.service-name }}/${{ inputs.environment }}
        param_value=${{ inputs.version }}
        aws ssm put-parameter --type String --overwrite --name $param_name --value $param_value
      shell: bash