name: 'py-install'
description: 'Install Python Dependencies'
runs:
  using: "composite"
  steps:
    - run: |
          if [ -f setup.py ]; then
               pip3 install -e '.[dev]'
          fi
          if [ -f requirements.txt ]; then
               pip3 install -r requirements.txt
               pip3 install -r requirements.txt -t dist/layers/common/python
          fi
          if [ -f requirements-dev.txt ]; then
               pip3 install -r requirements-dev.txt
          fi
          if [ -d src/functions ]; then
            for d in src/functions/*/ ; do
              func_name=$(basename "$"$d"")
              layer_path="dist/layers/functions/${func_name}/python"
              if [ -f "$d"/requirements.txt ]; then
                pip3 install -r "$d"/requirements.txt
                pip3 install -r "$d"/requirements.txt -t $layer_path
              fi
              if [ -f "$d"/requirements-dev.txt ]; then
                pip3 install -r "$d"/requirements-dev.txt
              fi
            done
          fi
          
          IFS=$'\n'
          set -f
          libraries_list=($(find . -maxdepth 1 -type d))
          export CURRENT_DIR=$(pwd)
          for d in $libraries_list; do
              cd $CURRENT_DIR
              if [ -f "$d/setup.py" ]; then    
                  cd $d
                  pip3 install --no-cache-dir -e '.[dev]'
              fi
          done
          
      shell: bash