name: 'py-install'
description: 'Install Python Dependencies'
runs:
  using: "composite"
  steps:
    - run: |
          if [ -f setup.py ]; then
               pip3 install -e '.[dev]'
          fi
          if [ -f requirements.txt ]; then
               pip3 install -r requirements.txt
          fi
          if [ -f requirements-dev.txt ]; then
               pip3 install -r requirements-dev.txt
          fi
          if [ -d src/functions ]; then
             func_path=src/functions
          elif [ -d src/lambdas ]; then
             func_path=src/lambdas
          else
             func_path=.
          fi
          if [ -d $func_path ]; then
            for d in $func_path/*/ ; do
              func_name=$(basename "$"$d"")
              layer_path="dist/layers/functions/${func_name}/python"
              if [ -f "$d"/requirements.txt ]; then
                pip3 install -r "$d"/requirements.txt
              fi
              if [ -f "$d"/requirements-dev.txt ]; then
                pip3 install -r "$d"/requirements-dev.txt
              fi
            done
          fi
          
          IFS=$'\n'
          set -f
          libraries_list=($(find . -maxdepth 1 -type d))
          export CURRENT_DIR=$(pwd)
          for d in $libraries_list; do
              cd $CURRENT_DIR
              if [ -f "$d/setup.py" ]; then    
                  cd $d
                  pip3 install -e '.[dev]'
              fi
          done
          
      shell: bash