name: "sign-version"
description: "Creates a named version from current RC pointers"
inputs:
  version:
    description: "The version name"
    required: true
  awsRegion:
    description: "The AWS region from which to get SSM parameters"
    required: true
  versionSpec:
    description: "The version spec to sign"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"
    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Run main script
      run: node index.js
      shell: bash
      working-directory: ${{ github.action_path }}
