name: "sign-version"
description: "Creates a named version from current RC pointers"
inputs:
  version:
    description: "The version name"
    required: true
  awsRegion:
    description: "The AWS region from which to get SSM parameters"
    required: true
  versionSpec:
    description: "The version spec to sign"
    required: false
runs:
  using: "composite"
  steps:
    - name: Change to action directory
      run: cd ${{ github.action_path }}
      shell: bash
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Run main script
      run: node index.js
      shell: bash
