name: 'sign-version'
description: 'Creates a named version from current RC pointers'
inputs:
  version:
    description: 'The version name'
    required: true
  awsRegion:
    description: 'The AWS region from which to get SSM parameters'
    required: true
  overrides:
    description: 'A map from service name to version'
    required: false
  hotfix:
    description: 'Version hotfix number'
    required: false
runs:
  using: 'node12'
  main: 'index.js'