name: "sign-version"
description: "Creates a named version from current RC pointers"
inputs:
  version:
    description: "The version name"
    required: true
  awsRegion:
    description: "The AWS region from which to get SSM parameters"
    required: true
  versionSpec:
    description: "The version spec to sign"
    required: false
runs:
  using: "node22"
  main: "index.js"
