name: 'env-get'
description: 'Deploys the environment'
inputs:
  env:
    description: 'The environment to deploy'
    required: true
  awsRegion:
    description: 'The target AWS region'
    required: true
outputs:
  services:
    description: 'A JSON array which configures the deployment of the current environment'
  stacks:
    description: 'CDK stacks to deploy'
runs:
  using: 'node12'
  main: 'index.js'