name: 'py-test'
description: 'Test python code'
runs:
  using: "composite"
  steps:
    - run: |
        pip install pytest==6.2.4
        pip install pytest-cov==2.12.1
        pip install moto==1.3.16
        pip install boto3==1.16.12
        pip install freezegun==1.0.0
        pytest ./test* --cov=./ --cov-report=xml
      shell: bash