name: 'py-test'
description: 'Test python code'
runs:
  using: "composite"
  steps:
    - run: |
        pip install pytest==6.2.4
        pip install pytest-cov==2.12.1
        pytest ./test* --cov=./ --cov-report=xml
      shell: bash