name: 'py-test'
description: 'Test python code'
runs:
  using: "composite"
  steps:
    - name: Run tests
      run: |
        
        if [ -d "test" ] || [ -d "tests" ] ; then
            test_dir=./test*
        else
            test_dir=./src
        fi
        
        pip install pytest-cov
        pytest $test_dir --cov=./ --cov-report=xml
      shell: bash

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: false