name: 'py-test'
description: 'Test python code'
runs:
  using: "composite"
  steps:
    - run: |
        
        if [ -d "test" ] || [ -d "tests" ] ; then
            test_dir=./test*
        else
            test_dir=./src
        fi
        
        pytest $test_dir
      shell: bash