name: 'resolve-dev-package-version'
description: 'Resolves the dev package name'
outputs:
  version:
    description: "Dev package version"
    value: ${{ steps.resolver.outputs.package_version }}
runs:
  using: "composite"
  
  steps:
    - shell: bash
      id: resolver
      run: |
          event_name=$GITHUB_EVENT_NAME
          echo github event name $event_name

          if [ "$event_name" = "pull_request" ]; then
            git_ref=$GITHUB_HEAD_REF
          else
            git_ref=$GITHUB_REF
          fi
          echo git ref $git_ref

          branch_name=$(echo $git_ref | sed -e 's/^refs\/heads\///')

          if [ "$branch_name" = "main" ] || [ "$branch_name" = "master" ]; then
            exit 1
          else
            user_name=$(echo $GITHUB_ACTOR | sed -e 's/[^[:alnum:]]+/_/g')
            user_name=$(echo $user_name | sed -e 's/\(.*\)/\L\1/')
            package_version=0.0.1-alpha-$user_name
            echo "::set-output name=package_version::$package_version"
          fi
      