name: 'update-rc'
description: 'Updates the service RC version'
runs:
  using: "composite"
  steps:
    - run: |
        service_name=$(echo $GITHUB_REPOSITORY | sed -e 's/^agwafarm\///')
        service_name=$(echo $service_name | sed -e 's/^agwa\-//')
        service_name=$(echo $service_name | sed -e 's/^\-service//')
        param_name=/infra/rc-version/$service_name

        param_value=$GITHUB_SHA

        echo ssm param name $param_name
        echo ssm param value $param_value
        
        aws ssm put-parameter --type String --overwrite --name $param_name --value $param_value
      shell: bash