name: 'pack'
description: 'Packakge RC for this service'
inputs:
  library-tag:
    description: 'Service Library tag to use'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
          app_service_name=${GITHUB_REPOSITORY//[_]/\-}
          echo deploying service $app_service_name
          s3_key_prefix=s3://agwa-cloud-lambda-sourcecode/$GITHUB_SHA/
          echo s3 prefix $s3_key_prefix
      shell: bash