name: 'pack'
description: 'Packakge RC for this service'
inputs:
  library-tag:
    description: 'Service Library tag to use'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
          app_service_name=$(echo $GITHUB_REPOSITORY | sed -e 's/^agwafarm\///')
          app_service_name=$(echo $app_service_name | sed -e 's/^agwa\-//')
          app_service_name=$(echo $app_service_name | sed -e 's/^\-service//')
          echo deploying service $app_service_name
          
          branch_name=$GITHUB_HEAD_REF
          echo branch name $branch_name

          rc_version=$GITHUB_SHA
          echo RC Version $GITHUB_SHA

          s3_key_prefix=s3://agwa-cloud-lambda-sourcecode/$app_service_name/$rc_version
          echo s3 prefix $s3_key_prefix
          
          branch_name=$(echo $GITHUB_HEAD_REF | sed -e 's/^refs\/heads\///')
          echo $branch_name

          if [ "$branch_name" = "main" ] || [ "$branch_name" = "master" ]; then
             echo "master branch"
          else
             echo "dev branch"
          fi
      shell: bash