name: 'parse-env'
description: 'Parse env variables'
outputs:
  stack-name:
    description: "Service Name"
    value: ${{ steps.packer.outputs.stack_name }}
  target-env:
    description: "Target environment"
    value: ${{ steps.packer.outputs.target_env }}
  service-name:
    description: "Service name"
    value: ${{ steps.packer.outputs.service_name }}
runs:
  using: "composite"
  steps:
    - run: |

          # Compute useful variables and outputs

          event_name=$GITHUB_EVENT_NAME
          echo github event name $event_name

          if [ "$event_name" = "pull_request" ]; then
             git_ref=$GITHUB_HEAD_REF
          else
             git_ref=$GITHUB_REF
          fi
          echo git ref $git_ref

          branch_name=$(echo $git_ref | sed -e 's/^refs\/heads\///')
          echo branch name $branch_name

          if [ "$branch_name" = "main" ] || [ "$branch_name" = "master" ]; then
             target_env=ci
             export AGWA_SERVICE_LIBRARY_TAG=latest
          else
             user_name=$(echo $GITHUB_ACTOR | sed -e 's/[^[:alnum:]]+/_/g')
             user_name=$(echo $user_name | sed -e 's/\(.*\)/\L\1/')
             echo user name $user_name 
             
             export AGWA_SERVICE_LIBRARY_TAG=edge-$user_name
             target_env=dev$user_name
          fi

          echo target env $target_env
          echo ::set-output name=target_env::$target_env
          
          service_name=$(echo $GITHUB_REPOSITORY | sed -e 's/^agwafarm\///')
          service_name=$(echo $service_name | sed -e 's/^agwa\-//')
          service_name=$(echo $service_name | sed -e 's/^\-service//')
          export SERVICE_NAME=$service_name
          echo service $service_name
          echo "::set-output name=service_name::$SERVICE_NAME"
          
          stack_name=$target_env-$service_name-service
          echo stack $stack_name
          export STACK_NAME=$stack_name
          echo "::set-output name=stack_name::$STACK_NAME"

      shell: bash
      id: packer