name: 'py-configure'
description: 'Configure Python'
runs:
  using: "composite"
  steps:
    - run: |
          export APP_CA_DOMAIN=agwafarm-private
          export APP_CA_REPOSITORY=agwafarm-private
          export APP_CA_DOMAIN_OWNER_ACCOUNT=953022346399
          export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain $APP_CA_DOMAIN --domain-owner $APP_CA_DOMAIN_OWNER_ACCOUNT --query authorizationToken --output text)
          aws codeartifact login --tool twine --repository $APP_CA_REPOSITORY --domain $APP_CA_DOMAIN --domain-owner $APP_CA_DOMAIN_OWNER_ACCOUNT
          pip config set global.extra-index-url https://aws:$CODEARTIFACT_AUTH_TOKEN@$APP_CA_DOMAIN-$APP_CA_DOMAIN_OWNER_ACCOUNT.d.codeartifact.us-west-2.amazonaws.com/pypi/$APP_CA_REPOSITORY/simple/
      shell: bash