name: 'agwa-install'
description: 'Install agwa package dependencies'
runs:
  using: "composite"
  steps:
    - run: |
          # Configure pip to use code artifact as additional pypi
          ca_domain=agwafarm-private
          ca_repo=agwafarm-private
          ca_account=953022346399
          ca_token=$(aws codeartifact get-authorization-token --domain $ca_domain --domain-owner $ca_account --query authorizationToken --output text)
          ca_region=us-west-2
          aws codeartifact login --tool twine --repository $ca_repo --domain $ca_domain --domain-owner $ca_account
          pip config set global.extra-index-url https://aws:$ca_token@$ca_domain-$ca_account.d.codeartifact.$ca_region.amazonaws.com/pypi/$ca_repo/simple/
          
          # Compute SERVICE LIB TAG
          event_name=$GITHUB_EVENT_NAME
          echo github event name $event_name

          if [ "$event_name" = "pull_request" ]; then
             git_ref=$GITHUB_HEAD_REF
          else
             git_ref=$GITHUB_REF
          fi
          echo git ref $git_ref

          branch_name=$(echo $git_ref | sed -e 's/^refs\/heads\///')
          echo branch name $branch_name

          if [ "$branch_name" = "main" ] || [ "$branch_name" = "master" ]; then
             export AGWA_SERVICE_LIBRARY_TAG=latest
          else
             user_name=$(echo $GITHUB_ACTOR | sed -e 's/[^[:alnum:]]+/_/g')
             user_name=$(echo $user_name | sed -e 's/\(.*\)/\L\1/')
             echo user name $user_name
             export AGWA_SERVICE_LIBRARY_TAG=edge-$user_name
          fi

          echo using library tag $AGWA_SERVICE_LIBRARY_TAG

          if [ -f "package-lock.json" ]; then
              npm ci
          elif [ -f "package.json" ]; then
              npm i
          fi

          python3 -m pip install -q -r requirements.txt
          python3 -m pip install -q -r requirements-dev.txt
          
          for d in src/lambdas/*/ ; do
            func_name=$(basename "$"$d"")  
            req_path=src/lambdas/${func_name}/requirements.txt
            if [ -f $req_path ]; then   
              python3 -m pip install -q -r $req_path
            fi
          done

      shell: bash
      id: installer