name: "publish-image"
on:
  workflow_dispatch:
    inputs:
      image:
        description: "Image"
        required: true
      version:
        description: "Version"
        required: true
      folder:
        description: "Build context"
        required: false
        default: "agwa-base"
      file:
        description: "Dockerfile"
        required: false
        default: "Dockerfile"
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      
      - name: "Checkout Repository"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: "Authenticate with AWS CLI"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: "Build Image"
        run: |
          cd ${{ github.event.inputs.folder }} && 
          docker build -f "agwafarm/${{ github.event.inputs.image }}" . -t "agwafarm/${{ github.event.inputs.image }}:${{ github.event.inputs.version }}" && 
          docker image push "agwafarm/${{ github.event.inputs.image }}" -a
