name: 'py-monorepo-install'
description: 'Install Python Monorepo Dependencies'
inputs:
  service-name:
    description: "Service Name"
    required: true
  version:
    description: "RC version"
    required: true
  environment:
    description: "Target environment"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
          # Compute Library Tag
          event_name=$GITHUB_EVENT_NAME
          echo github event name $event_name

          if [ "$event_name" = "pull_request" ]; then
             git_ref=$GITHUB_HEAD_REF
          else
             git_ref=$GITHUB_REF
          fi
          echo git ref $git_ref

          branch_name=$(echo $git_ref | sed -e 's/^refs\/heads\///')
          echo branch name $branch_name

          if [ "$branch_name" = "main" ] || [ "$branch_name" = "master" ]; then
             export AGWA_SERVICE_LIBRARY_TAG=latest
          else
             user_name=$(echo $GITHUB_ACTOR | sed -e 's/[^[:alnum:]]+/_/g')
             user_name=$(echo $user_name | sed -e 's/\(.*\)/\L\1/')
             echo user name $user_name 
             export AGWA_SERVICE_LIBRARY_TAG=edge_$user_name
          fi

          # Install Dependencies
          IFS=$'\n'
          set -f
          libraries_list=$(find . -maxdepth 1 -type d)
          export CURRENT_DIR=$(pwd)
          for d in $libraries_list; do
              cd $CURRENT_DIR
              if [ -f "$d/setup.py" ]; then
                  cd $d
                  pip3 install -I --no-cache-dir -e '.[dev]'
              fi
          done
          cd $CURRENT_DIR
      shell: bash